export const SET_RESET_PASSWORD_SUCCESS = 'SET_RESET_PASSWORD_SUCCESS';
export const SET_RESET_PASSWORD_ERROR = 'SET_RESET_PASSWORD_ERROR';
export const SET_RESET_PASSWORD_PENDING = 'SET_RESET_PASSWORD_PENDING';
export const SET_VAIDATE_OTP_SUCCESS = 'SET_VAIDATE_OTP_SUCCESS';
export const SET_FP_UPDATE_PASSWORD_SUCCESS='SET_FP_UPDATE_PASSWORD_SUCCESS';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_OTP = 'SET_OTP';