
export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_LOGIN_EMAIL = 'SET_LOGIN_EMAIL';
export const SET_MULTIFACTOR_LOGIN_SUCCESS = 'SET_MULTIFACTOR_LOGIN_SUCCESS';
export const SET_LOGIN_WITH_CODE_SUCCESS = 'SET_LOGIN_WITH_CODE_SUCCESS';
export const SET_LOGIN_REDIRECT_ON_AUTH_TYPE__SUCCESS = 'SET_LOGIN_REDIRECT_ON_AUTH_TYPE__SUCCESS';