export const SET_TFA = 'SET_TFA';
export const SET_QR_SUCCESS = 'SET_QR_SUCCESS';
export const SET_TFA_USERS_SUCCESS = 'SET_TFA_USERS_SUCCESS';
export const SET_TFA_ENABLE_SUCCESS = 'SET_TFA_ENABLE_SUCCESS';
export const SET_TFA_DISABLE_SUCCESS = 'SET_TFA_DISABLE_SUCCESS';
export const SET_REGENERATE_QR = 'SET_REGENERATE_QR';
export const SET_TFA_ERROR = 'SET_TFA_ERROR';